apiVersion: apps/v1
kind: Deployment
metadata:
 name: wisecow-deployment
 namespace: wise-deploy
 labels:
  app: wisecow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels: 
        app: wisecow
    spec:
     containers:
       - name: wisecow-image
         image: sriramravi477/cowsay:14143833899
         ports:
          - containerPort: 4499