apiVersion: v1
kind: Service
metadata:
  name: wisecow-service-deployment
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4499
      nodePort: 30011
  type: NodePort