name: workflow to deploy cowsay app to kubernetes
on: 
 push:
  branches:
    - main
jobs:
 deploy_kubernetes:
  runs-on: ubuntu-latest
  steps:
   - name: git checkout
     uses: actions/checkout@v4
   - name: configure docker
     uses: docker/setup-buildx-action@v3
   - name: push docker image to docker repository
     run: |
      docker build -t sriramravi477/cowsay:${{ github.run_id }} .
      docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
      docker push sriramravi477/cowsay:${{ github.run_id }}
   - name: config kubernetes
     run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        chmod +x kubectl
        mkdir -p ~/.local/bin
        mv ./kubectl ~/.local/bin/kubectl
   - name: deploy kubernetes
     run: |
      kubctl apply -f mainfest/
   - name: update image
     run: |
      kubectl set image deployment/wisecow-deployment wisecow-image=sriramravi477/cowsay:${{ github.run_id }}
      kubectl rollout status deployment/wisecow-deployment